services:

  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    restart: unless-stopped
    volumes:
      - ./unbound:/etc/unbound/custom.conf.d
    networks:
      dns_net:
        ipv4_address: 172.29.53.11

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    depends_on:
      - unbound
    environment:
      TZ: "${TZ}"
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "unbound#5335"
      FTLCONF_dns_revServers: "true,192.168.1.0/24,192.168.1.1,lan"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      dns_net:
        ipv4_address: 172.29.53.10

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    command: --cleanup --interval 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dns_net
      
networks:
  dns_net:
    name: dns_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.53.0/24