services:

  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    restart: unless-stopped
    volumes:
      - ./unbound:/etc/unbound/custom.conf.d
    networks:
      dns_net:
        ipv4_address: 172.29.53.11

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    depends_on:
      - unbound
    environment:
      TZ: "${TZ}"
      WEBPASSWORD: "${PIHOLE_PASSWORD}"
      DNSMASQ_LISTENING: "all"
      FTLCONF_REPLY_ADDR4: "${PIHOLE_IP}"
      PIHOLE_DNS_: "172.29.53.11#5335"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      dns_net:
        ipv4_address: 172.29.53.10
    dns:
      - 127.0.0.1
      - 172.29.53.11

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    command: --cleanup --interval 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dns_net

  #nebula-sync:
  #  image: ghcr.io/lovelaze/nebula-sync:latest
  #  container_name: nebula-sync
  #  restart: unless-stopped
  #  volumes:
  #    - ./backups:/data
  #  networks:
  #    - dns_net

networks:
  dns_net:
    name: dns_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.53.0/24